# Generated by Django 2.2.16 on 2022-07-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(default=1, verbose_name='Оценка'),
        ),
    ]
